### ISSUE TITLE
neoforge version of the mod is broken

### ISSUE THREAD

**Issue by GogUwU** [CodinGlitch/Lexiconfig#1]
[loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies: Mod ID: 'neoforge', Requested by: 'lexiconfig', Expected range: '[1,)', Actual version: '[MISSING]'

**Comment by CodinGlitch** [comment]
the forge version of Lexiconfig should be used for 1.20.1 instead of neoforge, as they are nearly identical in the version
